# Use a base image
FROM openjdk:11

# Set the working directory
WORKDIR /app

# Copy the application JAR file to the Docker image
COPY target/dataload-1.0-SNAPSHOT.jar /app/dataload-1.0-SNAPSHOT.jar

# Expose the application port
EXPOSE 8088

# Start the application
ENTRYPOINT ["java", "-jar", "/app/dataload-1.0-SNAPSHOT.jar"]
