# Use a base image
FROM openjdk:11-jdk-alpine

# Set the working directory
WORKDIR /app

# Copy the application JAR file to the Docker image
COPY target/mgt-1.0-SNAPSHOT.jar /app/mgt-1.0-SNAPSHOT.jar

# Expose the application port
EXPOSE 8087

# Start the application
ENTRYPOINT ["java", "-jar", "/app/mgt-1.0-SNAPSHOT.jar"]
